[System.Serializable]
public class GameDataString
{
    // This is going to be treated as a json version of GameData for when loading the game
    public string userCash;
    public string userXP;
    public string blocksMined;
    public string materialsSold;
    public string moneyEarned;
    public string playerPos;
    public string playerRotation;
    public string vehiclesOwned;
    public string currentVehicle;
    public string haulerCargo;
    // Uncollected materials
    public string materials;
    public string refineryInefficiency;
    public string refineryCapacity;
    public string refineryBattery;
    public string destroyedTilemapsTileValues;
    public string revealedTilemapsTileValues;
    public string seed;
    public string highestRow;
    public string mineInitialization;
    public string timerIndexes;
    public string rebirthProfitMultiplier;
    public string finishedTutorial;
    public string askedForReview;
    public string lastChallengeDate;
    public string challengeProgress;
    public string challengeCollection;
    public string superChallengeTimer;
    public string userGems;
    public string gemsEarned;
    public string currentOresMined;
    public string gemRewardsToCollect;
    public string tutorialScreenIndex;

    public GameDataString() {
        this.userCash = null;
        this.userXP = null;
        this.playerPos = null;
        this.playerRotation = null;
        this.blocksMined = null;
        this.materialsSold = null;
        this.moneyEarned = null;
        this.vehiclesOwned = null;
        this.currentVehicle = null;
        this.haulerCargo = null;
        this.materials = null;
        this.refineryInefficiency = null;
        this.refineryCapacity = null;
        this.refineryBattery = null;
        this.destroyedTilemapsTileValues = null;
        this.revealedTilemapsTileValues = null;        
        this.seed = null;
        this.highestRow = null;
        this.mineInitialization = null;
        this.timerIndexes = null;
        this.rebirthProfitMultiplier = null;
        this.finishedTutorial = null;
        this.askedForReview = null;
        this.lastChallengeDate = null;
        this.challengeProgress = null;
        this.challengeCollection = null;
        this.superChallengeTimer = null;
        this.userGems = null;
        this.gemsEarned = null;
        this.currentOresMined = null;
        this.gemRewardsToCollect = null;
        this.tutorialScreenIndex = null;
    }
}
